### ISSUE TITLE
Barrel shifted operands sometimes crash the transpiler

### ISSUE THREAD

**Issue by Shai-Aviv** [schorrm/arm2riscv#2]
Consider the following input:

```asm
	.arch armv8-a
	.file	"bug.c"
	.text
	.align	2
	.global	main
	.type	main, %function
main:
	add	w0, w0, w0, lsl 1
	ret
	.size	main, .-main
	.ident	"GCC: (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0"
	.section	.note.GNU-stack,"",@progbits
```

On my machine (Ubuntu 18.04 LTS running in Docker on RHEL 7.5), the output of `arm2riscv.py` for this input is distributed as follows:
* **55%** of times - the output is okay, no errors:

  ```asm
  	.file	"bug.c"
          .section .tdata
  REG_BANK:
          .dword 0
          .dword 0
          .dword 0
          .dword 0
          .dword 0
          .dword 0
          .dword 0
          .dword 0
  	.text
  	.align	2
  	.global	main
  	.type	main, %function
  main:
  	la	s5, REG_BANK
  	slliw	s10, a0, 1
  	addw	a0, a0, s10
  	ret
  	.size	main, .-main
  	.ident	"GCC: (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0"
  	.section	.note.GNU-stack,"",@progbits

  ```

* **23%** of times - I get this error:

  ```
  Traceback (most recent call last):
    File "./arm2riscv.py", line 89, in <module>
      buffer.append(instructions[op](op, [tmpreg, shifts['shift_reg'], shifts['shift_by']]))
    File "/home/shayaviv/arm2riscv/aarch64_instructions.py", line 49, in __init__
      self.specific_regs = safe_pullregs(operands)
    File "/home/shayaviv/arm2riscv/instr_helpers.py", line 18, in safe_pullregs
      if 'register' in o.keys():
  AttributeError: 'NoneType' object has no attribute 'keys'
  ```

* **22%** of times - I get a partial output:

  ```asm
  	.file	"bug.c"
          .section .tdata
  REG_BANK:
          .dword 0
          .dword 0
          .dword 0
          .dword 0
          .dword 0
          .dword 0
          .dword 0
          .dword 0
  	.text
  	.align	2
  	.global	main
  	.type	main, %function
  main:
  	la	s5, REG_BANK
  ```

  followed by this error:

  ```
  Traceback (most recent call last):
    File "./arm2riscv.py", line 125, in <module>
      line.emit_riscv()
    File "/home/shayaviv/arm2riscv/aarch64_instructions.py", line 176, in emit_riscv
      dest, s1, s2 = self.get_args()
  ValueError: too many values to unpack (expected 3)
  ```

I suspect that the bug has something to do with the random ordering of keys in Python's `dict` or `set` types, but I'm only guessing.

**Comment by schorrm** [comment]
In Python 3.6+ `dict` keys aren't randomly ordered, and I didn't use `set`s at all, so I'm really not sure what happened here. Trying to figure out.

**Comment by schorrm** [comment]
Tracked it down, it occurs at the grammar phase. Now to fix this.

**Comment by Shai-Aviv** [comment]
What a swift response! Thank you

**Comment by schorrm** [comment]
Fixed some issues with rules priorities, I think it should be addressed now (I just ran this about 30 times without a crash).
